### ISSUE TITLE
Unable to install 0.2.5 version

### ISSUE THREAD

**Issue by TrangPham** [sjmh/pyqb#18]
Python version 3.7

I can see the package here: https://pypi.org/project/pyqb/#history
When I look at the pip index I see: https://pypi.org/simple/pyqb/
```
pyqb-0.2.4-py2-none-any.whl
pyqb-0.2.4.tar.gz
pyqb-0.2.5-py2-none-any.whl
```

Is it missing the pyqb-0.2.5.tar.gz? Is that why I cannot install the newer version?

Sorry I'm not very familiar with the build of python packages

**Comment by ryboe** [comment]
It's missing a wheel for Python 3.
```
# we only have this on PyPI
pyqb-0.2.5-py2-none-any.whl

# we want one of these
pyqb-0.2.5-py2.py3-none-any.whl
pyqb-0.2.4-py3-none-any.whl
```

@sjmh Can you please drop Python 2 support and update this to Python 3?

**Comment by ryboe** [comment]
If anybody else if having problems using this package, try this workaround:

```toml
# pyproject.toml

[tool.poetry.dependencies]
pyqb = { git = "https://github.com/sjmh/pyqb.git" }
```
